### ISSUE TITLE
The php-oauth2-client library was deleted on github ?  

### ISSUE THREAD

**Issue by zhiyuazo** [fkooman/php-oauth-lib-rs#1]
Hi, fkooman:

As title...

**Comment by fkooman** [comment]
https://git.tuxed.net/fkooman/php-oauth2-client/

**Comment by zhiyuazo** [comment]
Thanks ，fkooman!

**Comment by fkooman** [comment]
https://gitlab.com/fkooman/php-oauth2-client this is now a mirror of my self-hosted copy.

**Comment by zhiyuazo** [comment]
Very thank you, fkooman .
